=== ROleP/masterjava-1/src/main/resources/myPayload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://rolep.net"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://rolep.net"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Group"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
                <xs:element name="Groups" type="xs:IDREFS" minOccurs="0" maxOccurs="1">
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="emailType" name="email" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:ID" name="projectID" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" name="description" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:ID" name="groupID" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element type="xs:IDREF" name="projectID" maxOccurs="1" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="groupType" name="type" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ROleP/masterjava-1/src/test/resources/myPayload.xml
<Payload xmlns="http://rolep.net"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://rolep.net myPayload.xsd">
    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com">
            <fullName>Full Name</fullName>
            <!--<city>Киев</city>-->
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru">
            <fullName>Admin</fullName>
            <groups>masterjava02 topjava10</groups>
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru">
            <fullName>Deleted</fullName>
            <groups>topjava09 topjava10</groups>
            <!--<city>Санкт-Петербург</city>-->
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project>
            <name>MasterJava</name>
            <description>Разработка полнофункционального многомодульного Maven проекта</description>
        </Project>
        <Project>
            <name>TopJava</name>
            <description>Наиболее востребованные технологии /инструменты / фреймворки Java Enterprise: Maven/ Spring/
                Security/ JPA(Hibernate)/ REST(Jackson)/ Bootstrap(CSS)/ jQuery + plugins</description>
        </Project>
    </Projects>
    <Groups>
        <Group groupType="CURRENT">
            <name>topjava10</name>
            <project>TopJava</project>
        </Group>
        <Group groupType="FINISHED">
            <name>TopJava09</name>
            <project>TopJava</project>
        </Group>
        <Group groupType="CURRENT">
            <name>masterjava02</name>
            <project>MasterJava</project>
        </Group>
    </Groups>
</Payload>
